site_name: OpenJones3D
theme:
  favicon: assets/images/favicon.svg
  name: material
  font:
    text: Libre Baskerville
  icon:
    logo: simple/redhat
    admonition:
      note: material/script-text
  palette:
    scheme: indy
  features:
    - navigation.indexes
extra_css:
  - assets/extra.css

extra:
  sidebar_title: 'Custom Sidebar Title'  # Custom title for the sidebar

repo_url: https://github.com/smlu/OpenJones3D/
repo_name: smlu/OpenJones3D

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: 'index.md'