site_name: OpenJones3D
theme:
  favicon: assets/img/favicon.svg
  name: material
  icon:
    logo: simple/redhat
    admonition:
      note: material/script-text
  palette:
    scheme: indy
  features:
    - navigation.indexes
    - navigation.top
extra_css:
  - assets/extra.css

repo_url: https://github.com/smlu/OpenJones3D/
repo_name: smlu/OpenJones3D

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - COG:
    - cog/index.md
    - AI COG functions: cog/cog_ai.md
    - Jones System COG functions: cog/cog_jones.md
    - Player COG functions: cog/cog_player.md
    - Sector COG functions: cog/cog_sector.md
    - Sound COG functions: cog/cog_sound.md
    - Surface COG functions: cog/cog_surface.md
    - System COG functions: cog/cog_system.md
    - Thing COG functions: cog/cog_thing.md
    - Voice COG functions: cog/cog_voice.md