site_name: Jones3D Docs
theme:
  name: material
  palette:
    scheme: indy
  features:
    - navigation.indexes
extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/smlu/OpenJones3D/
repo_name: smlu/OpenJones3D

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: 'index.md'